---
- type: remove
  path: /releases/name=consul
- type: remove
  path: /instance_groups/name=consul
- type: remove
  path: /instance_groups/name=adapter/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=scheduler/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=fake_logs_provider/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=fake_cups_provider/jobs/name=consul_agent

- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog/adapter/bosh_dns?
  value: true
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=scheduler/properties/scalablesyslog/scheduler/bosh_dns?
  value: true

- type: replace
  path: /instance_groups/name=adapter/jobs/name=metron_agent/consumes?
  value:
    doppler: {doppler: nil}
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=metron_agent/consumes?
  value:
    doppler: {doppler: nil}

- type: replace
  path: /instance_groups/name=adapter/jobs/-
  value: &bosh_dns_job
    name: bosh-dns
    release: bosh-dns
- type: replace
  path: /instance_groups/name=scheduler/jobs/-
  value: *bosh_dns_job
- type: replace
  path: /instance_groups/name=fake_cups_provider/jobs/-
  value: *bosh_dns_job
- type: replace
  path: /instance_groups/name=fake_logs_provider/jobs/-
  value: *bosh_dns_job

- type: replace
  path: /releases/-
  value:
    name: bosh-dns
    sha1: 0d55ec52b3a5c54a8284388d2400bf4c0172d7af
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release
    version: 0.0.8
