- type: replace
  path: /instance_groups/name=consul/persistent_disk_type?
  value: default

- type: replace
  path: /instance_groups/name=adapter/persistent_disk_type?
  value: default

- type: replace
  path: /instance_groups/name=scheduler/persistent_disk_type?
  value: default
