- type: replace
  path: /instance_groups/name=fake_logs_provider
  value:
    name: fake_logs_provider
    azs:
    - z1
    instances: 10
    persistent_disk_type: default
    vm_type: default
    stemcell: default
    networks:
    - name: default
    jobs:
    - name: fake_logs_provider
      release: scalablesyslog
      properties:
        fake_logs_provider:
          tls:
            ca: "((fake_logs_provider_tls.ca))"
            cert: "((fake_logs_provider_tls.certificate))"
            key: "((fake_logs_provider_tls.private_key))"
            cn: "reverselogproxy"
    - name: consul_agent
      release: consul
      consumes:
        consul: {from: consul_server}
      properties:
        consul:
          agent:
            services:
              logs:
                check:
                  name: dns_health_check
                  script: /var/vcap/jobs/fake_logs_provider/bin/dns_health_check

- type: replace
  path: /variables/-
  value:
    name: fake_logs_provider_tls
    type: certificate
    options:
      ca: common_ca
      common_name: reverselogproxy
      extended_key_usage:
      - client_auth
      - server_auth

- type: replace
  path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog/adapter/logs?
  value:
    addr: logs.service.cf.internal:8082
