name: scalablesyslog

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: scalablesyslog
  version: latest
- name: consul
  version: latest

instance_groups:
- name: consul
  azs:
  - z1
  instances: 1
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.244.0.34]
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul: nil
    provides:
      consul: {as: consul_server}
    properties:
      consul:
        agent:
          mode: server
          domain: cf.internal
          servers:
            lan: [10.244.0.34]
        require_ssl: true
        encrypt_keys:
        - "((consul_encrypt_key))"
        agent_cert: "((consul_agent.certificate))"
        agent_key: "((consul_agent.private_key))"
        ca_cert: "((consul_server.ca))"
        server_cert: "((consul_server.certificate))"
        server_key: "((consul_server.private_key))"
  update:
    serial: true
    max_in_flight: 1

- name: fake_cups_provider
  azs:
  - z1
  instances: 1
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: fake_cups_provider
    release: scalablesyslog
    properties:
      fake_cups_provider:
        tls:
          ca: "((fake_cups_provider_tls.ca))"
          cert: "((fake_cups_provider_tls.certificate))"
          key: "((fake_cups_provider_tls.private_key))"
  - name: consul_agent
    release: consul
    consumes:
      consul: {from: consul_server}
    properties:
      consul:
        agent:
          services:
            cups:
              check:
                name: dns_health_check
                script: /var/vcap/jobs/fake_cups_provider/bin/dns_health_check

- name: fake_logs_provider
  azs:
  - z1
  instances: 0
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default

- name: adapter
  azs:
  - z1
  instances: 3
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: consul_agent
    release: consul
    consumes:
      consul: {from: consul_server}
  - name: adapter
    release: scalablesyslog
    properties:
      scalablesyslog:
        adapter:
          tls:
            ca: "((adapter_tls.ca))"
            cert: "((adapter_tls.certificate))"
            key: "((adapter_tls.private_key))"
            cn: adapter
        adapter_rlp:
          tls:
            ca: "((adapter_rlp_tls.ca))"
            cert: "((adapter_rlp_tls.certificate))"
            key: "((adapter_rlp_tls.private_key))"
            cn: reverselogproxy

- name: scheduler
  azs:
  - z1
  instances: 1
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: scheduler
    release: scalablesyslog
    properties:
      scalablesyslog:
        scheduler:
          api:
            url: "https://cups.service.cf.internal:4433"
          tls:
            client:
              ca: "((scheduler_client_tls.ca))"
              cert: "((scheduler_client_tls.certificate))"
              key: "((scheduler_client_tls.private_key))"
              adapter_cn: "adapter"
            api:
              ca: "((scheduler_api_tls.ca))"
              cert: "((scheduler_api_tls.certificate))"
              key: "((scheduler_api_tls.private_key))"
              cn: "cups.service.cf.internal"
  - name: consul_agent
    release: consul
    consumes:
      consul: {from: consul_server}

variables:
- name: common_ca
  type: certificate
  options:
    is_ca: true
    common_name: CA
- name: scalable_syslog_ca
  type: certificate
  options:
    is_ca: true
    common_name: CA
- name: fake_cups_provider_tls
  type: certificate
  options:
    ca: common_ca
    common_name: cups.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: adapter_rlp_tls
  type: certificate
  options:
    ca: common_ca
    common_name: adapter-rlp
    extended_key_usage:
    - client_auth
    - server_auth
- name: scheduler_api_tls
  type: certificate
  options:
    ca: common_ca
    common_name: cups.service.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth
- name: adapter_tls
  type: certificate
  options:
    ca: scalable_syslog_ca
    common_name: adapter
    extended_key_usage:
    - server_auth
    - client_auth
- name: scheduler_client_tls
  type: certificate
  options:
    ca: scalable_syslog_ca
    common_name: scheduler
    extended_key_usage:
    - client_auth
- name: consul_encrypt_key
  type: password
- name: consul_agent_ca
  type: certificate
  options:
    is_ca: true
    common_name: consulCA
- name: consul_agent
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: consul_agent
    extended_key_usage:
    - client_auth
    - server_auth
- name: consul_server
  type: certificate
  options:
    ca: consul_agent_ca
    common_name: server.dc1.cf.internal
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
