name: scalablesyslog

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: scalablesyslog
  version: latest

instance_groups:
- name: scheduler
  azs:
  - z1
  instances: 1
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: scheduler
    release: scalablesyslog
  - name: fake_cups_provider
    release: scalablesyslog
    properties:
      fake_cups_provider:
        tls:
          ca: "((fake_cups_provider_tls.ca))"
          cert: "((fake_cups_provider_tls.certificate))"
          key: "((fake_cups_provider_tls.private_key))"

variables:
- name: common_ca
  type: certificate
  options:
    common_name: CA
- name: fake_cups_provider_tls
  type: certificate
  options:
    ca: common_ca
    common_name: localhost
    ext_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
