name: scalablesyslog

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: scalablesyslog
  version: latest

instance_groups:
- name: scheduler
  azs:
  - z1
  instances: 1
  persistent_disk_type: default
  vm_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: scheduler
    release: scalablesyslog

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
